version: 2
updates:
  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain Docker Base Image
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain NPM dependencies (for semantic-release)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
